<a href="https://colab.research.google.com/github/Staliber/AI-WORKSHOP/blob/main/DAY_2_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1.Create a 3x3 NumPy array with values 1 to 9.

In [3]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.Print only the first column.

In [8]:
print(arr1[:,0])

[1 4 7]


3.Print only the last row.

In [9]:
print(arr1[:,2])

[3 6 9]


4.Print the middle element

In [10]:
print(arr1[1,1])

5


5.Print the value 4 only

In [11]:
print(arr1[1,0])

4


6.Print the diagonal elements

In [13]:
print(np.diagonal(arr1)) #function to find diagonal elements of matrix

[1 5 9]


7.Reverse the rows

In [14]:
print(np.flipud(arr1)) #function to reverse rows

[[7 8 9]
 [4 5 6]
 [1 2 3]]


8.Replace all even numbers with 0

In [20]:
arr1[arr1 % 2 == 0] = 0 #first find even elements and then assign 0 to them
print(arr1)

[[1 0 3]
 [0 5 0]
 [7 0 9]]


9.Find Shape,Size,ndim,dtype

In [21]:
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

(3, 3)
9
2
int64


10.Find sum,mean,max and min

In [26]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.max(arr1))
print(np.min(arr1))

25
2.7777777777777777
9
0


11.Reshape a 1D array of 24 elements into (6,4) and (2,3,4)

In [37]:
arr2=np.arange(24)
reshape1=arr2.reshape(6,4)#function to reshape thea array
print(reshape1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [38]:
reshape2=arr2.reshape(2,3,4)#function to reshape thea array
print(reshape2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


12.Generate 20 random integers and compute mean,meadian and standard deviation

In [42]:
rand=np.random.rand(20)
print(rand)
print(np.mean(rand))
print(np.median(rand))
print(np.std(rand))

[0.67826418 0.90918603 0.92201844 0.75899414 0.17224914 0.40165896
 0.08878579 0.60079067 0.95206562 0.33906076 0.0822566  0.99431937
 0.07432003 0.41597996 0.21461747 0.94210343 0.01385616 0.34130615
 0.67067888 0.96279569]
0.526765373829214
0.5083853185613478
0.34245632540956733


13.Using boolean masking,print values greater than 50

In [55]:
arr3=np.array([12,34,45,67,79,94])
mask=arr3 > 50 #boolean masking is used to avoid writing explicit loops
print(arr3[mask])

[67 79 94]


14.Replace values less than 50 with 50

In [62]:
arr4=np.array([5,12,27,34,45,67,79,94,101,123])
mask=arr4 < 50
arr4[mask]=50
print(arr4)

[ 50  50  50  50  50  67  79  94 101 123]


15.Create two 3x3 matrices and perform addition,subtraction,matrix multiplication and transpose

In [75]:
a=np.array([[1,3,5],[7,9,11],[13,15,17]])
b=np.array([[2,4,6],[8,10,12],[14,16,18]])
arr_add=np.add(a,b)
arr_sub=np.subtract(a,b)
arr_mul=np.matmul(a,b)
arr_transpose=np.transpose(a)
arr_transpose2=np.transpose(b)

print(arr_add)


[[ 3  7 11]
 [15 19 23]
 [27 31 35]]


In [68]:
print(arr_sub)


[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [72]:
print(arr_mul)


[[ 96 114 132]
 [240 294 348]
 [384 474 564]]


In [70]:
print(arr_transpose)

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [76]:
print(arr_transpose2)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
